version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ci/Dockerfile
    container_name: app
    restart: on-failure
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 1s
      timeout: 5s
      retries: 10
    # depends_on:
    # volumes:
    #   - :
    ports:
      # - ":"
    networks:
      - network

networks:
  network: # this network
    driver: bridge

volumes:
