"""Instantiation

Revision ID: f5c7c02962b9
Revises:
Create Date: 2024-03-12 07:45:14.724736

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "f5c7c02962b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("timestamp_created", sa.DateTime(), nullable=False),
        sa.Column("email", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index("idx_id", "default", ["id"], unique=False)
    op.create_index(op.f("ix_default_id"), "default", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_default_id"), table_name="default")
    op.drop_index("idx_id", table_name="default")
    op.drop_table("default")
    # ### end Alembic commands ###
