execution:
  store_type: "sql"

logging:
  name: "TMPLT"
  environment: "local"
  level: "debug"  # TODO improve logic and consider uvicorn level
  output_file: "template.log"

db:
  user: ${CONTAINERISED_DB_USER}
  password: ${CONTAINERISED_DB_PASSWORD}
  host: ${CONTAINERISED_DB_HOST}
  port: ${CONTAINERISED_DB_PORT}
  name: ${CONTAINERISED_DB_NAME}
  migration_location: "src/adapters/database/migrations"

uvicorn:
  host: 0.0.0.0
  log_level: "debug"
  port: 80
